### ISSUE TITLE
Arelle FERC Renderer plugin 'render.py' throwing TypeError: Argument must be bytes or unicode, got 'NoneType'

### ISSUE THREAD

**Issue by nagsystrends** [xbrlus/ferc-renderer#13]
**I have tried FERC XBRL HTML rendering using arellecmdline.exe v1.4 as follows:**

C:\Program Files\Arelle>arellecmdline.exe --plugins "FERC/render" --ferc-render-render --ferc-render-template-set "http://github.com/xbrlus/ferc-renderer/raw/v1.4/RenderingTemplates/Form_1.zip" -f "D:/Work/eFinForms/XBRLs/2597/XBRL_1_2597_20210924044950.xbrl" --ferc-render-inline "D:/Work/eFinForms/XBRLs/2597/XBRL_1_2597_20210924044950.html" --ferc-render-css-file "C:\inetpub\wwwroot\eFinForms\wwwroot\assets\ferc-render-master\plugin\FERC\form-template.css" --ferc-render-inline-css --noCertificateCheck --ferc-render-debug

**I am getting following exception:**

[info] 2021-09-24 21:32:22.644372 Processing template 'Form 1 - 104 - Officers' -
Traceback (most recent call last):
  File "C:\Users\hermf\AppData\Local\Programs\Python\Python39\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 74, in run
  File "C:\Users\hermf\AppData\Local\Programs\Python\Python39\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
  File "arelleCmdLine.py", line 22, in <module>
  File "Z:\Users\arelle\hfdev\arelle\CntlrCmdLine.py", line 47, in main
  File "Z:\Users\arelle\hfdev\arelle\CntlrCmdLine.py", line 460, in parseAndRun
  File "Z:\Users\arelle\hfdev\arelle\CntlrCmdLine.py", line 942, in run
  File "C:\Program Files\Arelle\plugin\FERC\render.py", line 2085, in cmdLineXbrlLoaded
    render_report(cntlr, options, modelXbrl, *args, **kwargs)
  File "C:\Program Files\Arelle\plugin\FERC\render.py", line 2179, in render_report
    template_result = substituteTemplate(rule_meta_data,
  File "C:\Program Files\Arelle\plugin\FERC\render.py", line 721, in substituteTemplate
    footnote_page = build_footnote_page(template, template_number, footnotes, processed_footnotes, fact_number)
  File "C:\Program Files\Arelle\plugin\FERC\render.py", line 1246, in build_footnote_page
    inline_footnote, is_preformatted = create_inline_footnote_node(footnote['node'])
  File "C:\Program Files\Arelle\plugin\FERC\render.py", line 1318, in create_inline_footnote_node
    inline_footnote.set('{http://www.w3.org/XML/1998/namespace}lang', footnote_node.get('{http://www.w3.org/XML/1998/namespace}lang'))
  File "src\lxml\etree.pyx", line 816, in lxml.etree._Element.set
  File "src\lxml\apihelpers.pxi", line 593, in lxml.etree._setAttributeValue
  File "src\lxml\apihelpers.pxi", line 1538, in lxml.etree._utf8
**TypeError: Argument must be bytes or unicode, got 'NoneType'**

**Comment by campbellpryde** [comment]
Some questions:
Does the sample instance work  in your build?
Is it possible to send the  file XBRL_1_2597_20210924044950.xbrl directly to me? 
Did this file work in the previous version of the code?
Does it work with the updated rendering code for 1.5.

**Comment by nagsystrends** [comment]
Hi,

Please find the attached XBRL_1_2597_20210924044950.xbrl file which is causing this issue.



Please find the details for your questions:

1. Does the sample instance work in your build?

ANS: No

2. Is it possible to send the file XBRL_1_2597_20210924044950.xbrl directly to me?

ANS: Attached to the mail. PFA

3. Did this file work in the previous version of the code?
ANS:  I have tested the attached file in all previous versions (1.1,1.2,1.3,1.4,1.5). In all versions I am getting same exception.

4. Does it work with the updated rendering code for 1.5.

ANS: No


Thanks & Regards,
G.N.Murali Reddy
