### ISSUE TITLE
Arelle FERC Renderer plugin 'render.py' throwing TypeError: unsupported operand type(s) for -: 'list' and 'list'

### ISSUE THREAD

**Issue by nagsystrends** [xbrlus/ferc-renderer#8]
**I have tried FERC XBRL HTML rendering using arellecmdline.exe (FERC Renderer and Validation plugin (2021 Taxonomy)) as follows:**

arellecmdline.exe --plugin FERC/render --ferc-render-render --ferc-render-template-set "E:\lt\RenderingTemplates\Form_1_3Q_Electric.zip" -f "E:\\PennsylvaniaElectricCompany-136-2018Q1F1.xbrl" --ferc-render-css-file "C:\Program Files\Arelle\plugin\FERC\form-template.css" --ferc-render-inline-css --ferc-render-inline "E:\\PennsylvaniaElectricCompany-136-2018Q1F1.html" --noCertificateCheck --ferc-render-debug

**I am getting following exception:**

Traceback (most recent call last):
  File "C:\Users\hermf\AppData\Local\Programs\Python\Python39\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 74, in run
  File "C:\Users\hermf\AppData\Local\Programs\Python\Python39\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
  File "arelleCmdLine.py", line 22, in <module>
  File "Z:\Users\arelle\hfdev\arelle\CntlrCmdLine.py", line 47, in main
  File "Z:\Users\arelle\hfdev\arelle\CntlrCmdLine.py", line 457, in parseAndRun
  File "Z:\Users\arelle\hfdev\arelle\CntlrCmdLine.py", line 937, in run
  File "C:\Program Files\Arelle\plugin\FERC\render.py", line 2069, in cmdLineXbrlLoaded
    render_report(cntlr, options, modelXbrl, *args, **kwargs)
  File "C:\Program Files\Arelle\plugin\FERC\render.py", line 2217, in render_report
    dedup_id_full_document(main_html, fact_number)
  File "C:\Program Files\Arelle\plugin\FERC\render.py", line 2274, in dedup_id_full_document
    for elem in all_ids[dup_id] - xbrl_elements:
TypeError: unsupported operand type(s) for -: 'list' and 'list'

**Comment by campbellpryde** [comment]
Could you please send me the instance document you are using?

Campbell Pryde

President and CEO

XBRL US Inc.


***@***.*** ***@***.***>*

*https://xbrl.us <https://xbrl.us>*

+ 1 (917) 582-6159 (Mobile)


[image: XBRL US]

The non-profit community <https://xbrl.us/xusmembers> improving U.S.
reporting through a free, open standard
<https://xbrl.us/home/learn/free-open-standards/>.

**Comment by nagsystrends** [comment]
Hi Cambellpryde,

    Please find the attached instance document using to generate HTML using FERC render v1.0 causing issue Arelle FERC Renderer plugin 'render.py' throwing TypeError: unsupported operand type(s) for -: 'list' and 'list'


Thanks & Regards,
G.Nagamurali Reddy.
________________________________

**Comment by nagsystrends** [comment]
Hi Cambellpryde,
           I have sent the instance document causing issue Arelle FERC Renderer plugin in the below email. Please help me to resolve this issue.

Thanks & Regards,
G.Nagamurali Reddy.

**Comment by nagsystrends** [comment]
Hi Campbell,

          Any update on the below reported issue with FERC Renderer Release 1.0?.  I am again sending the instance XBRL document causing this issue.
         Please find the attachment. I appreciate your quick response.

Issue Details as follows FYI:

I have tried FERC XBRL HTML rendering using arellecmdline.exe (FERC Renderer and Validation plugin (2021 Taxonomy) - Release 1.0) for Form1 XBRL as follows:
arellecmdline.exe --plugin FERC/render --ferc-render-render --ferc-render-template-set "E:\RenderingTemplates\Form_1.zip" -f "E:\\WolverinePowerSupplyCooperativeInc-227-2018Q4F1.xbrl" --ferc-render-css-file "C:\Program Files\Arelle\plugin\FERC\form-template.css" --ferc-render-inline-css --ferc-render-inline "E:\\WolverinePowerSupplyCooperativeInc-227-2018Q4F1.html" --noCertificateCheck --ferc-render-debug
I am getting following exception:
Traceback (most recent call last):
  File "C:\Users\hermf\AppData\Local\Programs\Python\Python39\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 74, in run
  File "C:\Users\hermf\AppData\Local\Programs\Python\Python39\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
  File "arelleCmdLine.py", line 22, in <module>
  File "Z:\Users\arelle\hfdev\arelle\CntlrCmdLine.py", line 47, in main
  File "Z:\Users\arelle\hfdev\arelle\CntlrCmdLine.py", line 457, in parseAndRun
  File "Z:\Users\arelle\hfdev\arelle\CntlrCmdLine.py", line 937, in run
  File "C:\Program Files\Arelle\plugin\FERC\render.py", line 2082, in cmdLineXbrlLoaded
    render_report(cntlr, options, modelXbrl, *args, **kwargs)
  File "C:\Program Files\Arelle\plugin\FERC\render.py", line 2230, in render_report
    dedup_id_full_document(main_html, fact_number)
  File "C:\Program Files\Arelle\plugin\FERC\render.py", line 2287, in dedup_id_full_document
    for elem in all_ids[dup_id] - xbrl_elements:
TypeError: unsupported operand type(s) for -: 'list' and 'list'

Thanks & Regards,
G.Nagamurali Reddy.

From: Nagamurali.gudla
Sent: Saturday, June 12, 2021 4:01 AM
To: xbrlus/ferc-renderer ***@***.***>; xbrlus/ferc-renderer ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [xbrlus/ferc-renderer] Arelle FERC Renderer plugin 'render.py' throwing TypeError: unsupported operand type(s) for -: 'list' and 'list' (#8)

Hi Cambellpryde,

           I have sent the instance document causing issue Arelle FERC Renderer plugin in the below email. Please help me to resolve this issue.

Thanks & Regards,
G.Nagamurali Reddy.

**Comment by nagsystrends** [comment]
Issue Fixed
